/**
 * One-off: downloads the woff2 files for Manrope + DM Mono and writes them as
 * base64 @font-face rules to scripts/fonts-inline.css.
 *
 * Run once (needs network):  node scripts/fetch-fonts.mjs
 * After that the standalone build is fully offline.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))

// A modern browser UA makes the Google Fonts API serve woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Manrope:wght@300..800&family=DM+Mono:wght@400;500&display=swap'

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } })
if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status}`)
const css = await res.text()

// Split into individual @font-face blocks so each keeps its own descriptors.
const blocks = css.match(/@font-face\s*\{[^}]*\}/g) ?? []
console.log(`found ${blocks.length} @font-face blocks`)

const wanted = []
for (const block of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1]
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1] ?? ''
  const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim()
  const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? 'normal'
  if (!family || !url) continue

  // Latin only — the content is English. Keeps the payload small.
  const isLatin = range.includes('U+0000-00FF') || range.includes('U+0100-02AF')
  if (!isLatin) continue

  wanted.push({ family, url, range, weight, style })
}

console.log(`keeping ${wanted.length} latin subsets:`)

const parts = [
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
  '   Manrope and DM Mono are licensed under the SIL Open Font License 1.1. */',
  '',
]
let totalBytes = 0

for (const font of wanted) {
  const fontRes = await fetch(font.url, { headers: { 'User-Agent': UA } })
  if (!fontRes.ok) throw new Error(`font download failed: ${font.url}`)
  const buf = Buffer.from(await fontRes.arrayBuffer())
  totalBytes += buf.length
  const b64 = buf.toString('base64')
  console.log(`  ${font.family} ${font.weight} ${(buf.length / 1024).toFixed(1)}KB`)

  parts.push(
    '@font-face{',
    `font-family:'${font.family}';`,
    `font-style:${font.style};`,
    `font-weight:${font.weight};`,
    'font-display:swap;',
    `src:url(data:font/woff2;base64,${b64}) format('woff2');`,
    `unicode-range:${font.range};`,
    '}',
    '',
  )
}

const out = join(HERE, 'fonts-inline.css')
writeFileSync(out, parts.join('\n'), 'utf8')
console.log(
  `\nwrote ${out}\n  raw fonts ${(totalBytes / 1024).toFixed(0)}KB -> base64 CSS ${(
    Buffer.byteLength(parts.join('\n')) / 1024
  ).toFixed(0)}KB`,
)
